### ISSUE TITLE
信息提交和自动更新索引和统计数据草案

### ISSUE THREAD

**Issue by greatghoul** [eleduck/maskhero#1]
## TODO

- [x] 编写合并申请文件和更新 README 的脚本
- [ ] README TEMPLATE
- [ ] 配置 github webhook 用于响应 pull request merge 事件
- [ ] 一个 shell 脚本用于响应 webhook 拉代码，执行更新脚本(Python) 以及 push 代码
- [x] 找一个服务器自动跑这个流程

我在 draft 分支大致列现了文件结构

每个国家一个文件夹，有需要口罩的开发者，Fork项目后，在该文件夹下建立一个

```
<Unix Time Stamp>-<Github ID>.geo.json
```

的文件，用于填写自己的申请信息。

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "国家": "加拿大",
        "省": "A省",
        "市": "B市",
        "申请人": "邱建",
        "需要援助人数": 1,
        "需求数量": 20,
        "收到数量": 0,
        "备注": "无论如何，请不要太在意",
        "反馈": "",
        "marker-color": "#F3AE1A",
        "marker-symbol": "hospital"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.685,
          26.571
        ]
      }
    }
  ]
}
```

只需要提交这一个文件就可以了，分开提交文件是为了尽量减少冲突。

然后我们配置一个 github webhoook，在 PR merge 后，自动跑一个脚本，去更新国家和全球的索引，然后 commit and push

比如，加拿到下面的申请文件自动合并为

```
/Canada/index.geojson
```

合并的过程中，只从每个单独文件中抽取下面这一部分信息

![image](https://user-images.githubusercontent.com/208966/77290400-13146300-6d17-11ea-8760-e17107c815a1.png)

然后把各国家的信息再汇总为

```
/World/index.geojson
```

最后在 README 中更新所有国家和全世界的汇总

地区 | 申请人数 | 援助人数 | 需求口罩总数 | 收到口罩总数
---- | ---- | ---- | ---- | ----
Canada | 13 | 25 | 152 | 120
**World** | 13 | 25 | 152 | 120

目前这个脚本还没写好，在 

https://github.com/eleduck/maskhero/blob/draft/Scripts/update_index.py

**Comment by greatghoul** [comment]
我现在得去上班，得晚上才能继续写，下午哪位朋友要有时间把这个脚本完成，那非常欢迎。

**Comment by greatghoul** [comment]
现在 draft 里面的数据是我测试用的，后面会删除掉。

**Comment by greatghoul** [comment]
README 也会写一个固定的模板，用于嵌入这些数据来更新。

**Comment by greatghoul** [comment]
最终的效果类似这个仓库

https://github.com/ElaWorkshop/awesome-cn-cafe

![image](https://user-images.githubusercontent.com/208966/77291855-fcbbd680-6d19-11ea-9fd2-936a40a1ff24.png)

每个国家一个，然后全球再一个总的。

**Comment by greatghoul** [comment]
/World/index.geojson 文件，和每个申请者的 geo.json 的格式是完全相同的，唯一的区别是。

> 申请者的 geo.json 中"features": [] 里面只有一项，而 index 里面包含了所有。

我们需要做的是把 /<Country> 下面的的 geo.json 中的 features 中的内容全部合并到 index.geojson 中。

这里国家下面的就汇总到国家，每个国家的再汇总到全球 ./World/index.geojson

@Megatron7-code

**Comment by ghost** [comment]
我可以提供一个gce的服务器，干净的，大概能用一年😂

**Comment by greatghoul** [comment]
服务器已经找到了，谢谢你 @mufengcoding

**Comment by greatghoul** [comment]
根据大家的反馈，我们更改了需求，准备把受众扩大到所有海外化人华侨，此方案只适合程序员，所以会废弃掉。

多谢各位的帮忙了，新的动态，后续会在新的 issue 中讨论。
